# Generated by Django 5.1.6 on 2025-03-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='tbl_Users',
        ),
    ]
