# Generated by Django 5.1.6 on 2025-03-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_users_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='users_mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='users_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
