# Generated by Django 5.1.6 on 2025-03-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_users_users_mobile_users_users_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='users_name',
            new_name='users_email',
        ),
    ]
