# Generated by Django 5.1.6 on 2025-03-19 16:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_rename_users_name_users_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='users_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='users_email', unique=True),
        ),
    ]
