# Generated by Django 5.1.6 on 2025-03-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_users_users_name_users_users_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='users_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
