# Generated by Django 5.1.6 on 2025-03-31 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_users_users_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='tbl_Users',
        ),
    ]
