# Generated by Django 5.1.6 on 2025-04-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Employees_id', models.AutoField(primary_key=True, serialize=False)),
                ('Employees_firstname', models.CharField(max_length=100)),
                ('Employees_middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('Employees_lastname', models.CharField(max_length=100)),
                ('Employees_dateof_birth', models.DateField()),
                ('Employees_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('Employees_address', models.TextField()),
                ('Employees_mobile_number', models.CharField(max_length=15)),
                ('Employees_email', models.EmailField(max_length=254, unique=True)),
                ('Employees_highesteducation', models.CharField(max_length=200)),
                ('Employees_institutionsattended', models.CharField(max_length=200)),
                ('Employees_degreesearned', models.CharField(max_length=200)),
                ('Employees_certifications', models.CharField(blank=True, max_length=200, null=True)),
                ('Employees_vacationleave_balance', models.IntegerField(default=0)),
                ('Employees_sickleave_balance', models.IntegerField(default=0)),
                ('Employees_leavetypes', models.TextField(blank=True, null=True)),
                ('Employees_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Employees_payfrequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Bi-Weekly', 'Bi-Weekly'), ('Weekly', 'Weekly')], max_length=50)),
                ('Employees_accountnumber', models.CharField(max_length=30)),
                ('Employees_ifsccode', models.CharField(max_length=15)),
                ('Employees_accountholder_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('job_title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Terminated', 'Terminated')], max_length=50)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('Employees_emergencycontact_name', models.CharField(max_length=100)),
                ('Employees_emergencycontact_relationship', models.CharField(max_length=50)),
                ('Employees_emergencycontact_phone', models.CharField(max_length=15)),
                ('Employees_previous_employers', models.TextField(blank=True, null=True)),
                ('Employees_previous_jobtitles', models.TextField(blank=True, null=True)),
                ('Employees_previous_responsibilities', models.TextField(blank=True, null=True)),
                ('department_name', models.CharField(max_length=100)),
                ('department_birth', models.DateField(blank=True, null=True)),
                ('Employees_resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('Employees_iddocument', models.FileField(blank=True, null=True, upload_to='id_documents/')),
                ('Employees_certificationsdocument', models.FileField(blank=True, null=True, upload_to='certifications/')),
            ],
            options={
                'db_table': 'tbl_Employees',
            },
        ),
    ]
