# Generated by Django 5.1.6 on 2025-04-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='d_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
