# Generated by Django 5.1.6 on 2025-04-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_employees_d_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Employees_dateof_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
