# Generated by Django 5.1.6 on 2025-04-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0004_alter_employees_employees_vacationleave_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Employees_certificationsdocument',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Employees_iddocument',
            field=models.TextField(blank=True, null=True),
        ),
    ]
