# Generated by Django 5.1.6 on 2025-04-09 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_customer_customer_creditlimit_and_more'),
        ('master', '0004_alter_master_master_totalamount'),
        ('product', '0006_alter_product_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poschild',
            fields=[
                ('posch_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_qty', models.IntegerField()),
                ('item_mrp', models.FloatField(default=0.0)),
                ('item_saleprice', models.FloatField(default=0.0)),
                ('item_total', models.FloatField(default=0.0)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.master')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'tbl_poschild',
            },
        ),
    ]
