# Generated by Django 5.1.6 on 2025-03-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_customer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_CreditLimit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_CreditPeriod',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_gstno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_openingbal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_panno',
            field=models.IntegerField(null=True),
        ),
    ]
