# Generated by Django 5.1.6 on 2025-03-26 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Unit', '0002_remove_unit_unit_email_remove_unit_unit_mobile_and_more'),
        ('brand', '0001_initial'),
        ('category', '0001_initial'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_marathi_name', models.CharField(max_length=255)),
                ('product_HSNCode', models.CharField(max_length=255)),
                ('taxpercent', models.CharField(max_length=255)),
                ('taxtype', models.CharField(max_length=255)),
                ('alternateunit', models.IntegerField()),
                ('conversionfact', models.FloatField()),
                ('nos', models.IntegerField()),
                ('qrcode', models.IntegerField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase', models.IntegerField()),
                ('wholesaler', models.IntegerField()),
                ('distributor', models.IntegerField()),
                ('op_Qty', models.IntegerField()),
                ('op_Value', models.IntegerField()),
                ('mfg_Date', models.DateField()),
                ('exp_Date', models.DateField()),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tax.tax')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Unit.unit')),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
    ]
