# Generated by Django 5.1.6 on 2025-03-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_taxtype_alter_product_taxpercent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
