# Generated by Django 5.1.6 on 2025-03-13 16:23

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expenses_id', models.AutoField(primary_key=True, serialize=False)),
                ('expenses_name', models.CharField(max_length=255)),
                ('expenses_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='expenses_name', unique=True)),
            ],
        ),
    ]
