# Generated by Django 5.1.6 on 2025-03-13 06:25

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=255)),
                ('unit_email', models.CharField(max_length=255)),
                ('unit_mobile', models.CharField(max_length=255)),
                ('unit_password', models.CharField(max_length=255)),
                ('unit_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='unit_name', unique=True)),
            ],
        ),
    ]
