# Generated by Django 5.1.6 on 2025-03-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Unit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='unit_email',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_mobile',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_password',
        ),
    ]
