# Generated by Django 5.1.6 on 2025-04-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSRegistrationReport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregistrationreport',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='posregistrationreport',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='posregistrationreport',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='posregistrationreport',
            name='invoice_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='posregistrationreport',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='posregistrationreport',
            name='sale_type',
            field=models.CharField(choices=[('Cash', 'Cash Sale'), ('Credit', 'Credit Sale')], max_length=10),
        ),
    ]
