# Generated by Django 5.1.6 on 2025-04-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sale_type', models.CharField(choices=[('Cash', 'Cash Sale'), ('Credit', 'Credit Sale')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('invoice_no', models.CharField(max_length=50)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
    ]
