# Generated by Django 5.1.6 on 2025-04-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='master_itemname',
        ),
        migrations.RemoveField(
            model_name='master',
            name='master_mrp',
        ),
        migrations.RemoveField(
            model_name='master',
            name='master_qty',
        ),
        migrations.RemoveField(
            model_name='master',
            name='master_sale_price',
        ),
        migrations.RemoveField(
            model_name='master',
            name='master_total',
        ),
    ]
