# Generated by Django 5.1.6 on 2025-04-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_remove_master_master_itemname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='master_totalAmount',
            field=models.FloatField(default=0.0),
        ),
    ]
