# Generated by Django 5.1.6 on 2025-04-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_master_master_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='master_totalAmount',
            field=models.IntegerField(),
        ),
    ]
