# Generated by Django 5.1.6 on 2025-03-17 06:14

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentterms',
            fields=[
                ('Paymentterms_id', models.AutoField(primary_key=True, serialize=False)),
                ('Paymentterms_name', models.CharField(max_length=255)),
                ('Paymentterms_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Paymentterms_name', unique=True)),
            ],
            options={
                'db_table': 'tbl_Paymentterms',
            },
        ),
    ]
