# Generated by Django 5.1.6 on 2025-03-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPoints',
            fields=[
                ('RewardPoints_id', models.AutoField(primary_key=True, serialize=False)),
                ('RewardPoints_Maxrange', models.IntegerField(null=True)),
                ('RewardPoints_Minrange', models.IntegerField(null=True)),
                ('RewardPoints_Points', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tbl_RewardPoints',
            },
        ),
    ]
