# Generated by Django 5.1.6 on 2025-03-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_status',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='tbl_supplier',
        ),
    ]
