# Generated by Django 5.1.6 on 2025-03-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_remove_supplier_supplier_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_mobile',
            field=models.IntegerField(null=True),
        ),
    ]
