# Generated by Django 5.1.6 on 2025-03-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplier_supplier_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
