# Generated by Django 5.1.6 on 2025-03-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0011_supplier_supplier_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_CreditLimit',
            field=models.IntegerField(null=True),
        ),
    ]
