# Generated by Django 5.1.6 on 2025-03-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='Roles_BarcodePrint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='Roles_BusinessProfile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='Roles_Dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='Roles_HRDepartment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='Roles_POS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='Roles_Purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='Roles_RewardPoint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='Roles_Sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='Roles_Settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='Roles_Stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='Roles_Supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='Roles_UserProfile',
            field=models.BooleanField(default=False),
        ),
    ]
