# Generated by Django 5.1.6 on 2025-04-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0005_alter_roles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
