# Generated by Django 5.1.6 on 2025-03-15 04:40

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCharge',
            fields=[
                ('othercharge_id', models.AutoField(primary_key=True, serialize=False)),
                ('othercharge_name', models.CharField(max_length=255)),
                ('othercharge_type', models.CharField(max_length=255)),
                ('othercharge_amount', models.CharField(max_length=255)),
                ('othercharge_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='othercharge_name', unique=True)),
            ],
        ),
    ]
