# Generated by Django 5.1.6 on 2025-03-13 07:15

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentmode',
            fields=[
                ('Paymentmode_id', models.AutoField(primary_key=True, serialize=False)),
                ('Paymentmode_name', models.CharField(max_length=255)),
                ('Paymentmode_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Paymentmode_name', unique=True)),
            ],
            options={
                'db_table': 'tbl_Paymentmode',
            },
        ),
    ]
