# Generated by Django 5.1.6 on 2025-03-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('barcode_id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode_number', models.IntegerField()),
                ('barcode_img', models.ImageField(upload_to='barcode/')),
            ],
            options={
                'db_table': 'tbl_barcode',
            },
        ),
    ]
