# Generated by Django 5.1.6 on 2025-04-04 13:29

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('Sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('Sales_name', models.CharField(max_length=255)),
                ('Sales_addcashsale', models.BooleanField(default=False)),
                ('Sales_add_creditsale', models.BooleanField(default=False)),
                ('Sales_addcash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Sales_addcredit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Sales_addinvoicedate', models.DateField(blank=True, null=True)),
                ('Sales_add_duedays', models.IntegerField(blank=True, null=True)),
                ('Sales_add_duedate', models.DateField(blank=True, null=True)),
                ('Sales_addproductname', models.CharField(blank=True, max_length=255, null=True)),
                ('Sales_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Sales_name', unique=True)),
            ],
            options={
                'db_table': 'tbl_Sales',
            },
        ),
    ]
