# Generated by Django 5.1.6 on 2025-04-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_sales_sales_grand_total_sales_sales_invoice_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('sale_price', models.FloatField()),
                ('mrp', models.FloatField()),
                ('discount_percent', models.FloatField()),
                ('discount_value', models.FloatField()),
                ('basic_total', models.FloatField()),
                ('gst_percent', models.FloatField()),
                ('gst_value', models.FloatField()),
                ('total', models.FloatField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Sales.sales')),
            ],
        ),
    ]
