# Generated by Django 5.1.6 on 2025-04-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_saleitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
