# Generated by Django 5.1.6 on 2025-04-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_sales_sales_basic_total_sales_sales_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='Sales_price',
            field=models.FloatField(default=0),
        ),
    ]
